app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	// Authentication Routes
	Route::get('mezunadmin',function(){
		return view('special.index');
	});

	Route::get('mezunadmin/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
	Route::post('mezunadmin/login', 'Auth\AuthController@postLogin');
	Route::get('mezunadmin/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);


	// Categories
	Route::resource('categories', 'CategoryController', ['except' => ['create']]);
	Route::resource('tags', 'TagController', ['except' => ['create']]);

	
    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');
	Route::get('about', 'PagesController@getAbout');
	Route::get('/', 'PagesController@getIndex');
	Route::resource('posts', 'PostController');

	//Partners
	Route::get('/mezunadmin/partners','PartnerController@adminIndex');
	Route::post('/mezunadmin/partners/add','PartnerController@store');
	Route::get('/mezunadmin/partners/delete/{id}','PartnerController@delete');

	//Events
	Route::get('/mezunadmin/events','EventController@adminIndex');
	Route::post('/mezunadmin/events/add','EventController@store');
	Route::get('/mezunadmin/events/delete/{id}','EventController@delete');

	//Slider
	Route::get('/mezunadmin/slider','SliderController@adminIndex');
	Route::post('/mezunadmin/slider/add','SliderController@store');
	Route::get('/mezunadmin/slider/delete/{id}','SliderController@delete');


});


Route::get('/', 'PagesController@getindex');

// Route::get('/blog', function () {
//     return view('client.blog');
// });

Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

Route::get('/contact', function () {
    return view('client.contact');
});

Route::get('/gallery', 'BlogController@gallery');

Route::get('/partners', 'PartnerController@index');
Route::get('/partner/show/{id}','PartnerController@show');

Route::get('/events', 'EventController@index');
Route::get('/events/show/{id}','EventController@show');

// Auth::routes();

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    //
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Partner;

use Image;

class PartnerController extends Controller
{
    public function index(){
    	$partners = Partner::all();
    	return view('client.partners',compact('partners'));
    }

    public function adminIndex(){
    	$partners = Partner::all();
    	return view('partners.index',compact('partners'));
    }

    public function show($id){
        $partner = Partner::find($id);
        return view('client.partner',compact('partner'));
    }

    public function store(Request $request){

    	$new = new Partner;
    	$new->name = $request->name;
    	$new->about = $request->about;

    	if ($request->hasFile('logo')) {
          $image = $request->file('logo');
          $filename = time() . '.' . $image->getClientOriginalExtension();
          $location = public_path('images/partners/' . $filename);
          Image::make($image)->resize(800, 400)->save($location);

          $new->logo = $filename;
        }

        $new->save();
        return back();

    }

    public function delete($id){
    	$partner = Partner::find($id);
    	$partner->delete();
    	return back();
    }
}

resources/views/partners/index.blade.php
@extends('main')

@section('title', '| All Partners')

@section('content')

	<div class="row">
		<div class="col-md-10">
			<h1>All Partners</h1>
		</div>

		<div class="col-md-2">
			{{-- <a href="{{ route('posts.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Create New Post</a> --}}
		</div>
		<div class="col-md-12">
			<hr>
		</div>
	</div> <!-- end of .row -->

	<div class="row">
		<div class="col-md-12">
			<form action="{{url('/mezunadmin/partners/add')}}" method="post" enctype="multipart/form-data">
				<h2>Add Partner</h2>
				
				{{csrf_field()}}

				<input type="text" name="name" class="form-control" placeholder="Name">
				<br>
				<textarea placeholder="About..." name="about" class="form-control" cols="30" rows="10"></textarea>
				<br>
				<input type="file" name="logo" class="form-control">
				<br>
				<input type="submit" value="Add" class="btn btn-success">
				<br><br><br>

			</form>
		</div>

		<div class="col-md-12">
			<table class="table">
				<thead>
					<th>#</th>
					<th>Name</th>
					<th>About</th>
					<th>Logo</th>
					<th>Created at</th>
					<th>Actions</th>
				</thead>

				<tbody>
					
					@foreach ($partners as $partner)
						
						<tr>
							<th>{{ $partner->id }}</th>
							<td>{{ $partner->name }}</td>
							<td>{{ substr($partner->about,0,100)}}</td>
							<td>
								<img src="/images/partners/{{$partner->logo}}" style="max-width: 50px; max-height: 50px;">
							</td>
							<td>{{ date('M j, Y', strtotime($partner->created_at)) }}</td>
							<td><a href="{{url('mezunadmin/partners/delete',$partner->id)}}" class="btn btn-danger btn-sm">Delete</a></td>
							
						</tr>

					@endforeach

				</tbody>
			</table>

			<div class="text-center">
				{{-- {!! $posts->links(); !!} --}}
			</div>
		</div>
	</div>

@stop